#' @title Sample from trefoil knot
#'
#' @description These functions generate uniform samples from trefoil knot in
#'   3-dimensional space.
#'
#' @details The trefoil knot is the simplest nontrivial knot and contains three
#'   unique crossings in three dimensional space. This uniform sample is
#'   generated by rejection sampling. This process allows for simulation of
#'   random samples from the trefoil knot distribution, by using random samples
#'   from a more convenient distribution. It applies rejection/acceptance
#'   criterion such that the samples that are accepted are to be distributed as
#'   if they were from the target distribution. This function is adapted from
#'   Diaconis &al, 2013.
#'   
#' @name trefoil
#' @param n Number of observations.
#' @example inst/examples/ex-trefoil-knot.r

NULL

#' @rdname trefoil
#' @export

sample_trefoil <- function(n){
  theta <- rs_trefoil(n)
  # Applies modified theta values to parametric equation of trefoil knot
  res <- cbind(
    x = (sin(theta) + 2*sin(2*theta)),
    y = (cos(theta) - 2*cos(2*theta)),
    z = (-(sin(theta))^3)
  )
  
}

# Rejection sampler
rs_trefoil <- function(n){
  x <- c()
  # Keep looping until desired number of observations is achieved
  while (length(x) < n) {
    theta <- runif(n, 0, 2*pi)
    jacobian <- jd_trefoil(a)
    # Applies the Jacobian scalar value to each value of theta
    jacobian_theta <- sapply(theta, jacobian)
    # Density threshold is the greatest jacobian value in the trefoil knot, and
    # the area of least warping
    density_threshold <- runif(n, 0, jacobian(0))
    # Takes theta values that exceed the density threshold, and throws out the
    # rest
    x <- c(x, theta[jacobian_theta > density_threshold])
  }
  x[1:n]
}

# Jacobian determinant of trefoil
jd_trefoil <- function(a)
{
  function(theta)sqrt(
    ((cos(theta) + 4*cos(2*theta))^2) +
    ((-sin(theta) + 4*sin(2*theta))^2) + 
    (9*(cos(3*theta))^2)
    ) 
}

